"""Dodanie tabeli definijuących regiony do bazy danych i modeli

Revision ID: 1d61cff3ac48
Revises: 4cbe02e86a70
Create Date: 2025-05-28 22:03:13.304579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d61cff3ac48'
down_revision: Union[str, None] = '4cbe02e86a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region_cities', sa.Column('geonameid', sa.String(), nullable=True))
    op.add_column('region_cities', sa.Column('asciiname', sa.Text(), nullable=True))
    op.add_column('region_cities', sa.Column('alternatenames', sa.Text(), nullable=True))
    op.add_column('region_cities', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('region_cities', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('region_cities', sa.Column('feature_class', sa.String(), nullable=True))
    op.add_column('region_cities', sa.Column('feature_code', sa.String(), nullable=True))
    op.add_column('region_cities', sa.Column('admin1_code', sa.String(length=20), nullable=True))
    op.add_column('region_cities', sa.Column('admin2_code', sa.String(length=20), nullable=True))
    op.add_column('region_cities', sa.Column('admin3_code', sa.String(length=20), nullable=True))
    op.add_column('region_cities', sa.Column('admin4_code', sa.String(length=20), nullable=True))
    op.add_column('region_cities', sa.Column('population', sa.Numeric(), nullable=True))
    op.add_column('region_cities', sa.Column('elevation', sa.String(), nullable=True))
    op.add_column('region_cities', sa.Column('dem', sa.String(), nullable=True))
    op.add_column('region_cities', sa.Column('timezone', sa.Text(), nullable=True))
    op.add_column('region_cities', sa.Column('modification_date', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'region_cities', ['geonameid'])
    op.add_column('region_countries', sa.Column('geonameid', sa.String(), nullable=True))
    op.add_column('region_countries', sa.Column('asciiname', sa.Text(), nullable=True))
    op.add_column('region_countries', sa.Column('alternatenames', sa.Text(), nullable=True))
    op.add_column('region_countries', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.add_column('region_countries', sa.Column('population', sa.Numeric(), nullable=True))
    op.add_column('region_countries', sa.Column('timezone', sa.Text(), nullable=True))
    op.drop_constraint(op.f('region_countries_code_key'), 'region_countries', type_='unique')
    op.create_unique_constraint(None, 'region_countries', ['country_code'])
    op.create_unique_constraint(None, 'region_countries', ['geonameid'])
    op.drop_column('region_countries', 'code')
    op.add_column('region_states', sa.Column('geonameid', sa.String(), nullable=True))
    op.add_column('region_states', sa.Column('asciiname', sa.Text(), nullable=True))
    op.add_column('region_states', sa.Column('alternatenames', sa.Text(), nullable=True))
    op.add_column('region_states', sa.Column('admin1_code', sa.String(length=20), nullable=True))
    op.add_column('region_states', sa.Column('population', sa.Numeric(), nullable=True))
    op.add_column('region_states', sa.Column('timezone', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'region_states', ['geonameid'])
    op.drop_column('region_states', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region_states', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'region_states', type_='unique')
    op.drop_column('region_states', 'timezone')
    op.drop_column('region_states', 'population')
    op.drop_column('region_states', 'admin1_code')
    op.drop_column('region_states', 'alternatenames')
    op.drop_column('region_states', 'asciiname')
    op.drop_column('region_states', 'geonameid')
    op.add_column('region_countries', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'region_countries', type_='unique')
    op.drop_constraint(None, 'region_countries', type_='unique')
    op.create_unique_constraint(op.f('region_countries_code_key'), 'region_countries', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('region_countries', 'timezone')
    op.drop_column('region_countries', 'population')
    op.drop_column('region_countries', 'country_code')
    op.drop_column('region_countries', 'alternatenames')
    op.drop_column('region_countries', 'asciiname')
    op.drop_column('region_countries', 'geonameid')
    op.drop_constraint(None, 'region_cities', type_='unique')
    op.drop_column('region_cities', 'modification_date')
    op.drop_column('region_cities', 'timezone')
    op.drop_column('region_cities', 'dem')
    op.drop_column('region_cities', 'elevation')
    op.drop_column('region_cities', 'population')
    op.drop_column('region_cities', 'admin4_code')
    op.drop_column('region_cities', 'admin3_code')
    op.drop_column('region_cities', 'admin2_code')
    op.drop_column('region_cities', 'admin1_code')
    op.drop_column('region_cities', 'feature_code')
    op.drop_column('region_cities', 'feature_class')
    op.drop_column('region_cities', 'longitude')
    op.drop_column('region_cities', 'latitude')
    op.drop_column('region_cities', 'alternatenames')
    op.drop_column('region_cities', 'asciiname')
    op.drop_column('region_cities', 'geonameid')
    # ### end Alembic commands ###
