"""Dodanie tabeli definijuących regiony do bazy danych i modeli

Revision ID: 4cbe02e86a70
Revises: cabdbf11a3ce
Create Date: 2025-05-28 21:39:41.461388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbe02e86a70'
down_revision: Union[str, None] = 'cabdbf11a3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('region_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['region_countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['region_countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['region_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_cities')
    op.drop_table('region_states')
    op.drop_table('region_countries')
    # ### end Alembic commands ###
