"""Poprawa pola id w tabeli roles na autoinkrementowane

Revision ID: d942ee726abe
Revises: b6c92edb964b
Create Date: 2025-05-31 11:14:59.974918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd942ee726abe'
down_revision: Union[str, None] = 'b6c92edb964b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
